const STORAGE = { tools: 'borrowed.tools.v1', rentals: 'borrowed.rentals.v1', favorites: 'borrowed.favorites.v1' };
const ROLE_STORAGE = 'borrowed.user-role.v1';
const seedTools = [
  { id:'tn01',type:'hammer',name:'Fibreglass Claw Hammer',category:'Hand tools',emoji:'🔨',price:80,location:'Chennai',owner:'Arun K.',initial:'A',rating:4.9,reviews:18,quantity:3,available:true,color:'#f0dfcf',description:'A sturdy 16 oz claw hammer for home repairs, furniture work, and putting up shelves.' },
  { id:'tn02',type:'screwdriver',name:'Precision Screwdriver Set',category:'Hand tools',emoji:'🪛',price:60,location:'Coimbatore',owner:'Meena R.',initial:'M',rating:5.0,reviews:12,quantity:2,available:true,color:'#e6ead9',description:'A handy set of flathead and Phillips screwdrivers for electronics, appliances, and everyday fixes.' },
  { id:'tn03',type:'wrench',name:'Adjustable Spanner Wrench',category:'Hand tools',emoji:'🔧',price:70,location:'Salem',owner:'Karthik S.',initial:'K',rating:4.8,reviews:15,quantity:2,available:true,color:'#e4e8e9',description:'Adjustable jaw gives you a snug fit on nuts and bolts for plumbing and cycle repairs.' },
  { id:'tn04',type:'pliers',name:'Combination Pliers Set',category:'Hand tools',emoji:'🗜️',price:50,location:'Erode',owner:'Priya V.',initial:'P',rating:4.9,reviews:11,quantity:2,available:true,color:'#ede3d5',description:'Grip, bend, and cut wire with this useful set of insulated combination pliers.' },
  { id:'tn05',type:'hammer',name:'Rubber Mallet',category:'Hand tools',emoji:'🔨',price:55,location:'Kumbakonam',owner:'Suresh P.',initial:'S',rating:4.7,reviews:9,quantity:1,available:true,color:'#e8e5d8',description:'A soft-face mallet for assembling furniture and tapping pieces into place without marks.' },
  { id:'tn06',type:'tape',name:'5 Metre Measuring Tape',category:'Hand tools',emoji:'📏',price:30,location:'Thanjavur',owner:'Nila G.',initial:'N',rating:4.8,reviews:20,quantity:3,available:true,color:'#e9ead7',description:'Locking tape measure with easy-to-read markings for measuring rooms, wood, and furniture.' },
  { id:'tn07',type:'drill',name:'Cordless Drill Driver Kit',category:'Power tools',emoji:'🔩',price:250,location:'Coimbatore',owner:'Vijay R.',initial:'V',rating:5.0,reviews:32,quantity:2,available:true,color:'#e5ead9',description:'A versatile cordless drill for shelves, cabinets, and weekend DIY. Two batteries and bits included.' },
  { id:'tn08',type:'grinder',name:'Angle Grinder 4 inch',category:'Power tools',emoji:'⚙️',price:220,location:'Tiruppur',owner:'Fathima A.',initial:'F',rating:4.8,reviews:17,quantity:1,available:true,color:'#e9ded4',description:'Compact grinder for cutting metal, sharpening, and surface prep. Safety glasses included.' },
  { id:'tn09',type:'saw',name:'Circular Saw with Guide',category:'Power tools',emoji:'🪚',price:300,location:'Chennai',owner:'Dev M.',initial:'D',rating:4.9,reviews:24,quantity:1,available:true,color:'#eee1ce',description:'Make straight cuts through plywood and lumber. Includes a guide fence and spare blade.' },
  { id:'tn10',type:'sander',name:'Orbital Sheet Sander',category:'Workshop',emoji:'🪵',price:180,location:'Trichy',owner:'Anu B.',initial:'A',rating:4.8,reviews:14,quantity:1,available:true,color:'#e9ddd7',description:'Smooth wood surfaces and prepare furniture for paint or polish. Sandpaper sheets included.' },
  { id:'tn11',type:'ladder',name:'Aluminium Folding Ladder',category:'Home & repair',emoji:'🪜',price:160,location:'Namakkal',owner:'Muthu C.',initial:'M',rating:4.7,reviews:10,quantity:2,available:true,color:'#e3e3d9',description:'A stable step ladder for painting, ceiling fans, and reaching high shelves.' },
  { id:'tn12',type:'spade',name:'Garden Spade & Trowel',category:'Garden',emoji:'🌱',price:75,location:'Madurai',owner:'Kala T.',initial:'K',rating:4.9,reviews:19,quantity:2,available:true,color:'#dce8d9',description:'Get garden beds ready with this spade and hand trowel set. Great for planting and soil prep.' },
  { id:'tn13',type:'pipewrench',name:'Heavy Duty Pipe Wrench',category:'Home & repair',emoji:'🔧',price:90,location:'Salem',owner:'Bala N.',initial:'B',rating:4.8,reviews:13,quantity:1,available:true,color:'#e4e8e9',description:'A strong adjustable pipe wrench for household plumbing and fitting repairs.' },
  { id:'tn14',type:'socket',name:'Socket Wrench & Ratchet Set',category:'Hand tools',emoji:'🔩',price:110,location:'Namakkal',owner:'Ravi J.',initial:'R',rating:5.0,reviews:21,quantity:2,available:true,color:'#e5e8dc',description:'Metric sockets and a reversible ratchet for bikes, cars, and furniture assembly.' },
  { id:'tn15',type:'tilecutter',name:'Manual Tile Cutter',category:'Home & repair',emoji:'▰',price:280,location:'Kumbakonam',owner:'Mohan D.',initial:'M',rating:4.8,reviews:8,quantity:1,available:true,color:'#e9e3d8',description:'Score and snap ceramic tiles cleanly for kitchen and bathroom projects.' },
  { id:'tn16',type:'sprayer',name:'Electric Paint Sprayer',category:'Power tools',emoji:'🎨',price:260,location:'Chennai',owner:'Latha P.',initial:'L',rating:4.7,reviews:16,quantity:1,available:true,color:'#e9dce0',description:'Get an even finish on walls, fences, and furniture with an easy-clean paint sprayer.' },
  { id:'tn17',type:'grasscutter',name:'Electric Grass Trimmer',category:'Garden',emoji:'🌿',price:240,location:'Theni',owner:'Selvam R.',initial:'S',rating:4.9,reviews:15,quantity:1,available:true,color:'#dce8d9',description:'Tidy lawn edges and trim overgrowth. Extension lead and eye protection included.' },
  { id:'tn18',type:'pressurewasher',name:'Portable Pressure Washer',category:'Garden',emoji:'💦',price:320,location:'Erode',owner:'Geetha M.',initial:'G',rating:4.9,reviews:23,quantity:1,available:true,color:'#dbe7e9',description:'Refresh a patio, bike, or car with this compact pressure washer and spray attachments.' },
  { id:'tn19',type:'hedgetrimmer',name:'Cordless Hedge Trimmer',category:'Garden',emoji:'🌳',price:260,location:'Thanjavur',owner:'Mani S.',initial:'M',rating:4.8,reviews:12,quantity:1,available:true,color:'#dce8d9',description:'Lightweight cordless trimmer for keeping garden hedges and shrubs neat.' },
  { id:'tn20',type:'paintroller',name:'Paint Roller & Tray Kit',category:'Home & repair',emoji:'🖌️',price:65,location:'Madurai',owner:'Deepa V.',initial:'D',rating:4.7,reviews:18,quantity:3,available:true,color:'#e7e4dc',description:'Everything for a fresh coat: roller frame, two sleeves, extension pole, and tray.' },
  { id:'tn21',type:'wheelbarrow',name:'Garden Wheelbarrow',category:'Garden',emoji:'🛒',price:130,location:'Trichy',owner:'Naveen K.',initial:'N',rating:4.8,reviews:10,quantity:1,available:true,color:'#e5e8dc',description:'Move soil, compost, and garden waste around your yard with less effort.' },
  { id:'tn22',type:'plane',name:'Adjustable Block Plane',category:'Workshop',emoji:'🪵',price:85,location:'Tiruppur',owner:'Kavi S.',initial:'K',rating:4.9,reviews:7,quantity:1,available:true,color:'#ede3d5',description:'Trim and smooth wood edges for a tidy fit on doors, cabinets, and small furniture.' },
  { id:'tn23',type:'heatgun',name:'Variable Heat Gun',category:'Power tools',emoji:'♨️',price:140,location:'Dindigul',owner:'Siva P.',initial:'S',rating:4.7,reviews:9,quantity:1,available:true,color:'#eee0d4',description:'Useful for paint removal, heat-shrink tubing, and loosening old adhesive.' },
  { id:'tn24',type:'level',name:'Spirit Level & Chalk Line',category:'Workshop',emoji:'📐',price:55,location:'Vellore',owner:'Hema R.',initial:'H',rating:4.8,reviews:12,quantity:2,available:true,color:'#e2eadc',description:'Keep shelves, frames, and layouts straight with this level and snap chalk line.' },
  { id:'tn25',type:'screwdriver',name:'Insulated Electrician Tool Kit',category:'Home & repair',emoji:'🪛',price:120,location:'Karur',owner:'Gokul A.',initial:'G',rating:4.9,reviews:14,quantity:1,available:true,color:'#e5ead9',description:'Insulated screwdrivers and wire cutters for small electrical maintenance work.' },
  { id:'tn26',type:'cutter',name:'Bolt Cutter 18 inch',category:'Hand tools',emoji:'✂️',price:100,location:'Chennai',owner:'Babu T.',initial:'B',rating:4.8,reviews:11,quantity:1,available:true,color:'#e9ded4',description:'Long handles give extra leverage for cutting wire, chain, and small padlocks.' },
  { id:'tn27',type:'drill',name:'Cordless Impact Driver',category:'Power tools',emoji:'🔩',price:220,location:'Madurai',owner:'Madhan S.',initial:'M',rating:4.9,reviews:19,quantity:2,available:true,color:'#e5ead9',description:'Drive long screws and fasteners quickly with this compact impact driver and two batteries.' },
  { id:'tn28',type:'saw',name:'Variable Speed Jigsaw',category:'Power tools',emoji:'🪚',price:210,location:'Chennai',owner:'Ramesh K.',initial:'R',rating:4.8,reviews:14,quantity:1,available:true,color:'#eee1ce',description:'Cut curves and shapes in wood, laminate, and thin metal with adjustable speed control.' },
  { id:'tn29',type:'drill',name:'Rotary Hammer Drill',category:'Power tools',emoji:'🔩',price:360,location:'Coimbatore',owner:'Shalini P.',initial:'S',rating:4.9,reviews:28,quantity:1,available:true,color:'#e5ead9',description:'Power through masonry and concrete for anchors, fittings, and renovation work.' },
  { id:'tn30',type:'grinder',name:'Bench Grinder 6 inch',category:'Power tools',emoji:'⚙️',price:170,location:'Erode',owner:'Nandha V.',initial:'N',rating:4.7,reviews:12,quantity:1,available:true,color:'#e4e8e9',description:'Sharpen garden tools and clean up metal edges with this dual-wheel bench grinder.' },
  { id:'tn31',type:'plane',name:'Electric Wood Planer',category:'Power tools',emoji:'🪵',price:240,location:'Namakkal',owner:'Sathya R.',initial:'S',rating:4.8,reviews:9,quantity:1,available:true,color:'#ede3d5',description:'Level timber and smooth door edges with adjustable cutting depth and dust bag.' },
  { id:'tn32',type:'saw',name:'Reciprocating Saw',category:'Power tools',emoji:'🪚',price:230,location:'Salem',owner:'Imran A.',initial:'I',rating:4.8,reviews:16,quantity:1,available:true,color:'#eee1ce',description:'A versatile demolition saw for pruning, renovation, and rough cuts through timber.' },
  { id:'tn33',type:'drill',name:'Woodworking Router Kit',category:'Power tools',emoji:'🪵',price:260,location:'Thanjavur',owner:'Bhuvana S.',initial:'B',rating:5.0,reviews:10,quantity:1,available:true,color:'#e5ead9',description:'Shape edges, cut grooves, and add a clean finish to shelves and furniture.' },
  { id:'tn34',type:'sprayer',name:'Inverter Arc Welding Machine',category:'Power tools',emoji:'⚡',price:480,location:'Tiruppur',owner:'Aravind M.',initial:'A',rating:4.9,reviews:17,quantity:1,available:true,color:'#dbe4e7',description:'Portable inverter welder for gates, brackets, and small fabrication jobs. Mask and gloves included.' },
  { id:'tn35',type:'pressurewasher',name:'Portable Air Compressor',category:'Power tools',emoji:'💨',price:310,location:'Chennai',owner:'Vetri K.',initial:'V',rating:4.7,reviews:13,quantity:1,available:true,color:'#dbe7e9',description:'Inflate tyres and power small pneumatic tools with this portable air compressor.' },
  { id:'tn36',type:'drill',name:'Electric Screw Gun',category:'Power tools',emoji:'🪛',price:150,location:'Trichy',owner:'Janani R.',initial:'J',rating:4.8,reviews:11,quantity:2,available:true,color:'#e5ead9',description:'Drive many screws comfortably while assembling cabinets, decks, and drywall.' },
  { id:'tn37',type:'grinder',name:'Electric Metal Cut-off Saw',category:'Power tools',emoji:'⚙️',price:300,location:'Kumbakonam',owner:'Kishore T.',initial:'K',rating:4.8,reviews:8,quantity:1,available:true,color:'#e4e8e9',description:'Make quick, straight cuts through metal rods and angle iron for workshop projects.' },
  { id:'tn38',type:'sander',name:'Car & Furniture Polisher',category:'Power tools',emoji:'✨',price:190,location:'Theni',owner:'Malar S.',initial:'M',rating:4.9,reviews:15,quantity:1,available:true,color:'#e9ddd7',description:'Bring back a smooth shine on car paint, stone, and furniture finishes.' },
  { id:'tn39',type:'drill',name:'Concrete Demolition Hammer',category:'Power tools',emoji:'🔨',price:520,location:'Madurai',owner:'Sridhar P.',initial:'S',rating:4.8,reviews:18,quantity:1,available:true,color:'#e5ead9',description:'Break up concrete and remove old tile during renovation. Chisels and carry case included.' },
  { id:'tn40',type:'grinder',name:'Dual Action Sander Grinder',category:'Power tools',emoji:'⚙️',price:210,location:'Vellore',owner:'Prakash D.',initial:'P',rating:4.7,reviews:10,quantity:1,available:true,color:'#e4e8e9',description:'An adaptable workshop tool for smoothing surfaces and light edge preparation.' },
  { id:'tn41',type:'drill',name:'Corded Hammer Drill',category:'Power tools',emoji:'🔩',price:180,location:'Karur',owner:'Gowri N.',initial:'G',rating:4.8,reviews:12,quantity:1,available:true,color:'#e5ead9',description:'A reliable hammer drill for masonry holes, wall fixtures, and home installation.' },
  { id:'tn42',type:'saw',name:'Mini Circular Trim Saw',category:'Power tools',emoji:'🪚',price:200,location:'Dindigul',owner:'Elango S.',initial:'E',rating:4.8,reviews:9,quantity:1,available:true,color:'#eee1ce',description:'A lighter saw for plywood panels, laminate cuts, and quick workshop jobs.' },
  { id:'tn43',type:'sprayer',name:'Paint Spray Gun & Compressor',category:'Power tools',emoji:'🎨',price:340,location:'Erode',owner:'Nirmala K.',initial:'N',rating:4.9,reviews:13,quantity:1,available:true,color:'#e9dce0',description:'A smooth, even spray finish for furniture, doors, and small renovation projects.' },
  { id:'tn44',type:'grasscutter',name:'Electric Leaf Blower',category:'Garden',emoji:'🍃',price:175,location:'Ooty',owner:'Karthika M.',initial:'K',rating:4.8,reviews:11,quantity:1,available:true,color:'#dce8d9',description:'Clear dry leaves from a driveway and tidy garden paths after a weekend outside.' },
  { id:'tn45',type:'ladder',name:'Telescopic Work Platform',category:'Home & repair',emoji:'🪜',price:210,location:'Tirunelveli',owner:'Sundar B.',initial:'S',rating:4.7,reviews:7,quantity:1,available:true,color:'#e3e3d9',description:'A compact folding work platform for painting and indoor repair tasks.' }
];
const read = (key, fallback) => { try { const data = JSON.parse(localStorage.getItem(key)); return Array.isArray(data) ? data : fallback; } catch { return fallback; } };
const savedTools = read(STORAGE.tools, seedTools);
const oldDemoData = savedTools.some(tool => ['Portland','Gresham','Beaverton','Milwaukie'].includes(tool.location));
const catalogNeedsRefresh = !oldDemoData && savedTools.some(tool => tool.id==='tn26') && !savedTools.some(tool => tool.id==='tn45');
const savedById = new Map(savedTools.map(tool=>[tool.id,tool]));
let tools = oldDemoData ? seedTools : catalogNeedsRefresh ? [...seedTools.map(tool=>savedById.get(tool.id)||tool),...savedTools.filter(tool=>!seedTools.some(seed=>seed.id===tool.id))] : savedTools;
let rentals = oldDemoData ? [] : read(STORAGE.rentals, []);
let favorites = oldDemoData ? [] : read(STORAGE.favorites, []);
let activeCategory = 'All';
let activeView = 'marketplace';
let toastTimer;
let pendingToolImage = '';
let userRole = localStorage.getItem(ROLE_STORAGE) === 'shopkeeper' ? 'shopkeeper' : 'customer';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const dayString = date => { const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0'); return `${y}-${m}-${d}`; };
const today = dayString(new Date());
const datePlus = (date, days) => { const value=new Date(`${date}T12:00:00`); value.setDate(value.getDate()+days); return dayString(value); };
const prettyDate = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}) : 'Choose a date';
const daysBetween = (start,end) => Math.max(1, Math.round((new Date(`${end}T12:00:00`)-new Date(`${start}T12:00:00`))/86400000)+1);
const money = value => `₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
function persist(){ localStorage.setItem(STORAGE.tools,JSON.stringify(tools)); localStorage.setItem(STORAGE.rentals,JSON.stringify(rentals)); localStorage.setItem(STORAGE.favorites,JSON.stringify(favorites)); }
function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),2600); }
function overlaps(aStart,aEnd,bStart,bEnd){ return aStart<=bEnd && bStart<=aEnd; }
function reservedCount(toolId,start,end){ return rentals.filter(r=>r.toolId===toolId && r.status!=='Returned' && r.status!=='Cancelled' && overlaps(r.startDate,r.endDate,start,end)).reduce((sum,r)=>sum+(Number(r.quantity)||1),0); }
function availability(tool,start,end){ return Math.max(0,(Number(tool.quantity)||1)-reservedCount(tool.id,start,end)); }
function dates(){ const start=$('#search-date').value||today; return {start,end:$('#return-date').value||start}; }
function availableTools(){ const {start,end}=dates(); return tools.filter(t=>t.available!==false && availability(t,start,end)>0); }
function inferToolType(name=''){
  const n=name.toLowerCase();
  if(n.includes('screwdriver'))return'screwdriver';
  if(n.includes('impact driver')||n.includes('driver drill')||n.includes('drill')||n.includes('compressor'))return n.includes('compressor')?'pressurewasher':'drill';
  if(n.includes('hammer')||n.includes('mallet'))return'hammer';
  if(n.includes('wrench')||n.includes('spanner'))return n.includes('pipe')?'pipewrench':'wrench';
  if(n.includes('plier'))return'pliers';
  if(n.includes('saw')||n.includes('jigsaw'))return'saw';
  if(n.includes('ladder')||n.includes('platform'))return'ladder';
  if(n.includes('tape')||n.includes('measuring'))return'tape';
  if(n.includes('spade')||n.includes('shovel'))return'spade';
  if(n.includes('socket')||n.includes('ratchet'))return'socket';
  if(n.includes('grinder')||n.includes('cut-off')||n.includes('cutoff'))return'grinder';
  if(n.includes('sander')||n.includes('polisher'))return'sander';
  if(n.includes('tile cutter'))return'tilecutter';
  if(n.includes('sprayer')||n.includes('welder')||n.includes('welding'))return'sprayer';
  if(n.includes('grass')||n.includes('hedge')||n.includes('blower'))return'grasscutter';
  if(n.includes('washer'))return'pressurewasher';
  if(n.includes('roller'))return'paintroller';
  if(n.includes('wheelbarrow'))return'wheelbarrow';
  if(n.includes('plane')||n.includes('planer'))return'plane';
  if(n.includes('router'))return'drill';
  if(n.includes('heat gun'))return'heatgun';
  if(n.includes('level')||n.includes('chalk'))return'level';
  if(n.includes('cutter'))return'cutter';
  return'hammer';
}
function toolArt(tool){if(tool.imageData&&/^data:image\/(?:jpeg|webp|png);base64,[a-z0-9+/]+=*$/i.test(tool.imageData))return `<img class="tool-photo" src="${tool.imageData}" alt="Photo of ${esc(tool.name)}">`;const id=`art-${String(tool.id).replace(/[^a-z0-9]/gi,'')}`;let shape='';switch(tool.type||inferToolType(tool.name)){
 case'hammer':shape='<g transform="rotate(-34 90 73)"><path d="M82 54h18v67H82z" fill="#be7540"/><path d="M96 58h5v61h-5z" fill="#e3a05e"/><path d="M55 43h68v22H55z" fill="#505b62"/><path d="M55 43h68l-8 8H61z" fill="#879198"/><path d="M55 43v22l8 7V51z" fill="#303b43"/><path d="M115 43h9v22h-9z" fill="#364047"/><path d="M64 47h47" stroke="#b6bec0" stroke-width="2"/></g>';break;
 case'screwdriver':shape='<g transform="rotate(31 90 73)"><path d="M87 24h7v61h-7z" fill="#879195"/><path d="M89 21h4v11h-4z" fill="#d0d4d2"/><path d="M78 77q0-7 7-9h11q7 2 7 9v29q0 11-11 11h-3q-11 0-11-11z" fill="#d9663f"/><path d="M82 79v25q0 7 6 8v-43q-6 2-6 10" fill="#ef9661"/><path d="M86 87h12M86 94h12M86 101h12" stroke="#f7c49c" stroke-width="2"/></g>';break;
 case'wrench':case'pipewrench':shape='<g transform="rotate(-39 90 72)"><path d="M83 52h17v67H83z" fill="#77838a"/><path d="M95 55h5v61h-5z" fill="#aeb6b7"/><path d="M83 59 62 39l8-10 24 22z" fill="#79858b"/><path d="m100 52 23-22 9 9-23 23z" fill="#aab2b4"/><path d="M62 39 56 22l12 9 7-11 7 20-12 11z" fill="#505b62"/><path d="m121 30 13-9-2 17-10 10-10-10z" fill="#69757b"/><path d="M86 61v49" stroke="#e0e4e1" stroke-width="2"/></g>';break;
 case'pliers':shape='<g transform="rotate(28 90 73)"><path d="m85 72-27 47-10-5 27-49z" fill="#384d43"/><path d="m94 72 29 46 10-6-29-46z" fill="#d36946"/><path d="m78 56 9 15-18-18-9-22 8-5 17 20z" fill="#899398"/><path d="m102 56-9 15 18-18 9-22-8-5-17 20z" fill="#b8c0bf"/><circle cx="90" cy="69" r="9" fill="#303c39"/><circle cx="90" cy="69" r="3" fill="#e5bb75"/></g>';break;
 case'drill':shape='<g transform="rotate(-12 90 73)"><path d="M41 46q0-12 12-12h52q11 0 11 12v34H41z" fill="#d8a82e"/><path d="M48 39h54v8H48z" fill="#f3cc56"/><path d="M69 78h31l-5 44q-1 9-11 9H72l-10-32z" fill="#35473f"/><path d="m68 84 12 3-6 35h-8z" fill="#54705d"/><path d="M113 48h28v22h-28z" fill="#879297"/><path d="M138 54h20v10h-20z" fill="#4a565b"/><path d="M157 57h11v4h-11z" fill="#bbc2c2"/><path d="M48 48h7v18h-7z" fill="#f4e7b2"/><circle cx="91" cy="56" r="9" fill="#66716b"/><circle cx="91" cy="56" r="4" fill="#28372f"/><path d="M81 129h34q5 0 5 7H78q0-7 3-7" fill="#c75d3d"/></g>';break;
 case'saw':case'tilecutter':shape='<g transform="rotate(-28 90 72)"><path d="M45 70 115 42l29 56-78 28z" fill="#bcc1bd"/><path d="M49 74 113 50l20 42-69 25z" fill="#e0e3dc"/><path d="m57 108 9 11-8 4-8-12zM75 101l9 11-8 4-8-12zM93 94l9 11-8 4-8-12zM111 87l9 11-8 4-8-12z" fill="#59645e"/><path d="M77 57q8-14 24-20l19 24q-14-3-21 11z" fill="#d56d48"/><path d="M84 57q8-7 15-8l10 13q-9 1-14 7z" fill="#efaa75"/><path d="M49 75 115 51" stroke="#faf9f3" stroke-width="3"/></g>';break;
 case'ladder':shape='<g transform="rotate(8 90 73)"><path d="M57 24 73 27 49 120 37 117z" fill="#aab2b0"/><path d="M104 21 119 25 96 121 82 118z" fill="#77848a"/><path d="m53 42 55 8-3 8-55-8zM48 62l55 8-3 8-55-8zM43 83l55 8-3 8-55-8zM38 104l55 8-3 8-55-8z" fill="#d9ded8"/><path d="m60 30 44 86" stroke="#ffffff" stroke-opacity=".7" stroke-width="3"/></g>';break;
 case'tape':shape='<g transform="rotate(-22 90 70)"><path d="M62 50q0-13 14-13h42q14 0 14 13v42q0 14-14 14H76q-14 0-14-14z" fill="#d6a728"/><path d="M69 49h49q8 0 8 8v9H69z" fill="#f1ca43"/><path d="M80 72h44v23H80z" fill="#35463d"/><path d="M123 75h29v14h-29z" fill="#bcc2bc"/><path d="M143 75h11v5h-11z" fill="#e2e3db"/><circle cx="96" cy="84" r="9" fill="#d3a231"/><circle cx="96" cy="84" r="4" fill="#f1d264"/><path d="M76 55h38" stroke="#fff0b2" stroke-width="2"/></g>';break;
 case'spade':shape='<g transform="rotate(-30 90 72)"><path d="M86 32h10v72H86z" fill="#b77944"/><path d="M80 25h22v8H80z" fill="#3d5446"/><path d="M75 100h33l-4 22q-13 12-26 0z" fill="#68777a"/><path d="M80 105h23" stroke="#d1d8d2" stroke-width="2"/><path d="M90 39v58" stroke="#dda66b" stroke-width="2"/></g>';break;
 case'socket':shape='<g transform="rotate(-28 90 72)"><path d="m76 51 14-13 14 13v44H76z" fill="#78848a"/><path d="m82 51 8-8 8 8v39H82z" fill="#c3c9c7"/><path d="M90 90v31h9V90M94 110h34v9H94z" fill="#626f75"/><path d="M127 111h8v8h-8z" fill="#c0c6c4"/><path d="M82 57h16" stroke="#f4f3e8" stroke-width="2"/></g>';break;
 case'grinder':case'sander':shape='<g transform="rotate(-24 90 72)"><path d="M51 49h64q12 0 12 12v16H51z" fill="#d6a52c"/><path d="M58 42h48v9H58z" fill="#f0c94d"/><path d="M91 76h30v38H91z" fill="#3d4b43"/><path d="M98 83h15v24H98z" fill="#607365"/><path d="M127 56h25v14h-25z" fill="#707b7f"/><path d="M144 58h15v10h-15z" fill="#c0c5c1"/><ellipse cx="71" cy="88" rx="24" ry="10" fill="#48564f"/><ellipse cx="71" cy="85" rx="24" ry="9" fill="#aeb5b1"/><ellipse cx="71" cy="83" rx="19" ry="6" fill="#dadbd3"/></g>';break;
 case'sprayer':case'pressurewasher':shape='<g transform="rotate(-10 90 72)"><path d="M53 42h63q10 0 10 10v42H53z" fill="#d59d32"/><path d="M60 48h51v9H60z" fill="#f2c451"/><path d="M66 94h41v26H66z" fill="#47584d"/><path d="M73 101h26v7H73z" fill="#94a291"/><path d="M126 57h20v13h-20z" fill="#69777b"/><path d="M141 60h20v7h-20z" fill="#aab3b2"/><path d="M102 57q29-21 33-7" fill="none" stroke="#354b41" stroke-width="5"/><path d="M62 40h43" stroke="#fae4a1" stroke-width="3"/></g>';break;
 case'grasscutter':case'hedgetrimmer':shape='<g transform="rotate(-28 90 72)"><path d="M83 36h12v59H83z" fill="#68757a"/><path d="M76 28h27v16H76z" fill="#d4a82e"/><path d="M80 31h18v7H80z" fill="#f3ce56"/><path d="M85 91h8v23h-8z" fill="#3f5146"/><path d="M66 114h49v9H66z" fill="#8e9a9b"/><path d="M59 123h63v6H59z" fill="#c3c9c6"/><path d="M83 49h12v32H83z" fill="#f0bd40"/></g>';break;
 case'paintroller':shape='<g transform="rotate(-25 90 72)"><path d="M54 38h79v26H54z" fill="#d7d8cf"/><path d="M59 43h68v16H59z" fill="#faf9ef"/><path d="M88 63h8v39h-8z" fill="#78858a"/><path d="M91 98v15h20v8H85v-22z" fill="#b3bbc0"/><path d="M55 46h75" stroke="#d4ddd4" stroke-width="2"/></g>';break;
 case'wheelbarrow':shape='<g transform="rotate(-9 90 72)"><path d="m48 48 85 7-19 48H68z" fill="#6d9671"/><path d="m53 53 72 7-16 34H72z" fill="#9cbe8d"/><path d="M47 49 29 43M46 53l-18 7M114 101l23 12M67 99 51 116" stroke="#59676b" stroke-width="5" stroke-linecap="round"/><circle cx="134" cy="116" r="15" fill="#4b5757"/><circle cx="134" cy="116" r="6" fill="#bdc4bd"/><path d="M62 46h50" stroke="#dce9ce" stroke-width="3"/></g>';break;
 case'plane':shape='<g transform="rotate(-28 90 72)"><path d="M60 45h64v66H60z" fill="#bc7951"/><path d="M66 51h51v53H66z" fill="#dbad65"/><path d="M72 58h39v33H72z" fill="#626f71"/><path d="M78 63h27v24H78z" fill="#b2b9b5"/><path d="M82 64v21" stroke="#eef0e5" stroke-width="3"/><path d="M61 100h61v11H61z" fill="#8a5e46"/></g>';break;
 case'heatgun':shape='<g transform="rotate(-15 90 72)"><path d="M44 44h74q9 0 9 9v23q0 9-9 9H44z" fill="#d45e42"/><path d="M52 49h57v9H52z" fill="#ef9670"/><path d="M75 82h32v31q0 8-9 8H82z" fill="#384940"/><path d="M126 50h23v28h-23z" fill="#8b9699"/><path d="M146 56h20v16h-20z" fill="#c0c6c2"/><path d="M164 60h8v8h-8z" fill="#707b7d"/><path d="M57 44h44" stroke="#f7c2a4" stroke-width="3"/></g>';break;
 case'level':shape='<g transform="rotate(-19 90 72)"><path d="M43 60h99v25H43z" fill="#d3a82f"/><path d="M49 64h87v5H49z" fill="#efcc56"/><path d="M83 68h25v11H83z" rx="5" fill="#35453c"/><rect x="87" y="71" width="17" height="5" rx="2.5" fill="#b5d994"/><path d="M51 74h13M122 74h12" stroke="#fff1bc" stroke-width="2"/></g>';break;
 case'cutter':shape='<g transform="rotate(-32 90 72)"><path d="M75 36h31v76q0 12-15 12T75 112z" fill="#d36c49"/><path d="M80 43h21v63H80z" fill="#f09a6d"/><path d="M79 50h24v7H79zM79 63h24v7H79zM79 76h24v7H79z" fill="#ae4e36"/><path d="M85 32h13v10H85z" fill="#b8c1c1"/><path d="M89 20h5v15h-5z" fill="#899497"/><path d="M82 103h17" stroke="#f7c5a1" stroke-width="2"/></g>';break;
 default:shape='<g transform="rotate(-22 90 72)"><path d="M57 46h66v65H57z" fill="#d7a83a"/><path d="M64 53h48v10H64z" fill="#f2ce59"/><path d="M73 74h36v27H73z" fill="#405248"/><path d="M80 81h22v13H80z" fill="#a8b5a5"/></g>';
 }
 return `<svg class="tool-art-svg" viewBox="0 0 180 140" role="img" aria-label="3D illustration of ${esc(tool.name)}"><defs><linearGradient id="${id}-metal" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#f5f5ed"/><stop offset=".48" stop-color="#aeb8b7"/><stop offset="1" stop-color="#59656a"/></linearGradient><linearGradient id="${id}-orange" x1="0" y1="0" x2=".8" y2="1"><stop stop-color="#f0ad64"/><stop offset="1" stop-color="#bd5439"/></linearGradient></defs><ellipse cx="91" cy="119" rx="47" ry="9" fill="#29372d" opacity=".13"/><g stroke="#303b39" stroke-opacity=".24" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round">${shape}</g><path d="M42 112q43 13 94-1" fill="none" stroke="#fff" stroke-opacity=".38" stroke-width="2"/></svg>`;
}
function card(tool,index=0,small=false){ const {start,end}=dates(); const count=availability(tool.id,start,end); const saved=favorites.includes(tool.id); if(small) return `<article class="suggestion-card"><div class="suggestion-art" style="--art-bg:${esc(tool.color||'#e8ebde')}">${toolArt(tool)}</div><div><h4>${esc(tool.name)}</h4><p>${money(tool.price)} / day · ${esc(tool.location)}</p></div><button aria-label="View ${esc(tool.name)}" data-book="${esc(tool.id)}">↗</button></article>`;
  return `<article class="tool-card" style="animation-delay:${Math.min(index*55,330)}ms"><div class="tool-art" style="--art-bg:${esc(tool.color||'#e8ebde')}"><span class="tool-art-badge">${count<=1?'JUST ONE LEFT':'READY TO BORROW'}</span><button class="heart-button ${saved?'saved':''}" data-favorite="${esc(tool.id)}" aria-label="${saved?'Remove from':'Add to'} favorites">${saved?'♥':'♡'}</button>${toolArt(tool)}</div><div class="tool-card-body"><div class="tool-meta"><span class="tool-category">${esc(tool.category)}</span><span class="tool-rating"><b>★</b> ${Number(tool.rating||4.8).toFixed(1)} <span>(${Number(tool.reviews||0)})</span></span></div><h3 class="tool-name" style="font-size:20px!important;line-height:1.05!important">${esc(tool.name)}</h3><div class="tool-owner"><span class="owner-dot">${esc(tool.initial||'H')}</span> ${esc(tool.owner||'Local host')} · ${esc(tool.location)}, Tamil Nadu</div><div class="tool-card-footer"><strong class="tool-price">${money(tool.price)}<span> / day</span></strong><span class="tool-availability"><i class="availability-dot"></i>${count} available</span><button class="tool-detail-button" data-book="${esc(tool.id)}">Rent it <span>↗</span></button></div></div></article>`;
}
function runSearch(){ const query=$('#search-query').value.trim().toLowerCase(); const location=$('#search-location').value.trim().toLowerCase(); const {start,end}=dates(); let matches=availableTools().filter(t=>(activeCategory==='All'||t.category===activeCategory)&&(!query||`${t.name} ${t.category} ${t.description}`.toLowerCase().includes(query))&&(!location||t.location.toLowerCase().includes(location)||location.includes(t.location.toLowerCase()))); $('#tool-grid').innerHTML=matches.length?matches.map(card).join(''):`<div class="empty-state"><span style="font-size:28px">⌕</span><strong>No tools found for those dates.</strong>Try another date, widen your location, or see our nearby alternatives below.</div>`; $('#results-copy').textContent=`${matches.length} ${matches.length===1?'tool':'tools'} available · ${prettyDate(start)}${end!==start?' – '+prettyDate(end):''}`; const suggestionSection=$('#suggestion-section'); if(matches.length){suggestionSection.classList.add('hidden');return;} const fallback=tools.filter(t=>t.available!==false&&availability(t.id,start,end)>0&&(activeCategory==='All'||t.category===activeCategory||!tools.some(x=>x.category===activeCategory))).filter(t=>!location||!t.location.toLowerCase().includes(location)||Boolean(query&&!`${t.name} ${t.category} ${t.description}`.toLowerCase().includes(query))).slice(0,3); if(!fallback.length){suggestionSection.classList.add('hidden');return;} $('#suggestion-grid').innerHTML=fallback.map(t=>card(t,0,true)).join(''); suggestionSection.classList.remove('hidden'); }
 function updateRoleUI(){const shopkeeper=userRole==='shopkeeper';$('#nav-rentals').classList.toggle('hidden',shopkeeper);$('#nav-shopkeeper').classList.toggle('hidden',!shopkeeper);$('#host-banner').classList.toggle('hidden',shopkeeper);$('#profile-button').textContent=shopkeeper?'S':'C';$('#profile-button').setAttribute('aria-label',`Current role: ${shopkeeper?'Shopkeeper':'Customer'}. Change role`);$$('.role-choice').forEach(button=>{const selected=button.dataset.role===userRole;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});}
 function changeRole(role,notify=true){userRole=role==='shopkeeper'?'shopkeeper':'customer';localStorage.setItem(ROLE_STORAGE,userRole);updateRoleUI();if($('#role-dialog').open)$('#role-dialog').close();setView('marketplace');if(notify)toast(`${userRole==='shopkeeper'?'Shopkeeper':'Customer'} role selected.`);}
 function setView(view){if(view==='rentals'&&userRole!=='customer'){toast('Choose the Customer role to view My rentals.');return;}if(view==='admin'&&userRole!=='shopkeeper'){toast('Choose the Shopkeeper role to open the Host desk.');$('#role-dialog').showModal();return;}activeView=view; const marketIds=['home','marketplace','how-it-works']; marketIds.forEach(id=>$('#'+id).classList.toggle('hidden',view!=='marketplace')); $('#host-banner').classList.toggle('hidden',view!=='marketplace'||userRole==='shopkeeper'); $('#rentals-view').classList.toggle('hidden',view!=='rentals'); $('#admin-view').classList.toggle('hidden',view!=='admin'); $$('.nav-link').forEach(link=>link.classList.toggle('active',link.dataset.view===view)); if(view==='rentals')renderRentals(); if(view==='admin')renderAdmin(); window.scrollTo({top:0,behavior:'smooth'}); }
function statusFor(rental){ if(rental.status==='Returned'||rental.status==='Cancelled')return rental.status; if(rental.status==='Rented')return new Date(`${rental.endDate}T23:59:59`)<new Date()? 'Overdue':'Rented'; if(rental.endDate<today)return 'Overdue'; return 'Reserved'; }
function statusClass(status){return `status-${status.toLowerCase()}`;}
function renderRentals(){ $('#rental-count').textContent=rentals.filter(r=>r.status!=='Returned'&&r.status!=='Cancelled').length; if(!rentals.length){$('#rentals-list').innerHTML='<div class="empty-rentals"><span>🧰</span><h3>Your next project starts here.</h3><p>You have no rentals yet. Find a neighbor’s tool and get making.</p><button class="button button-dark" data-view="marketplace">Explore tools <span>↗</span></button></div>';return;} $('#rentals-list').innerHTML=rentals.slice().reverse().map(r=>{const tool=tools.find(t=>t.id===r.toolId);const status=statusFor(r);return `<article class="rental-row"><div><h3>${tool?toolArt(tool):esc(tool?.emoji||'🧰')} ${esc(r.toolName||tool?.name||'Tool')}</h3><p>Booking ${esc(r.id)} · ${prettyDate(r.startDate)} – ${prettyDate(r.endDate)} · ${Number(r.quantity)||1} item(s) · ${money(r.total)}</p><p>Pickup: ${esc(tool?.location||r.location||'Local host')} · ${esc(r.renterName)}</p></div><span class="status-pill ${statusClass(status)}"><i class="availability-dot"></i>${esc(status)}</span><div class="rental-actions">${status==='Reserved'?`<button data-cancel="${esc(r.id)}">Cancel request</button>`:''}${status==='Rented'?`<button data-return="${esc(r.id)}">Mark returned</button>`:''}</div></article>`;}).join('');}
function renderAdmin(){const active=rentals.filter(r=>!['Returned','Cancelled'].includes(statusFor(r))).length;$('#admin-stats').innerHTML=`<div class="stat-card"><span>Listed tools</span><strong>${tools.length}</strong></div><div class="stat-card"><span>Active rentals</span><strong>${active}</strong></div><div class="stat-card"><span>Hosts nearby</span><strong>${new Set(tools.map(t=>t.owner)).size}</strong></div><div class="stat-card"><span>Average rating</span><strong>4.8<span style="font-size:13px;color:#c28b34"> ★</span></strong></div>`;
  $('#admin-rentals-list').innerHTML=rentals.length?rentals.slice().reverse().map(r=>`<div class="admin-rental-row"><div><strong>${esc(r.toolName||'Tool')} · ${esc(r.renterName)}</strong><span>${esc(r.id)} · ${prettyDate(r.startDate)} → ${prettyDate(r.endDate)} · ${esc(statusFor(r))}</span></div><select aria-label="Update rental status" data-status="${esc(r.id)}"><option ${statusFor(r)==='Reserved'?'selected':''}>Reserved</option><option ${statusFor(r)==='Rented'?'selected':''}>Rented</option><option ${statusFor(r)==='Returned'?'selected':''}>Returned</option></select></div>`).join(''):'<div class="empty-rentals"><span>↗</span><h3>No rental requests yet</h3><p>New bookings will show up here.</p></div>';
  $('#admin-inventory-list').innerHTML=`<div class="inventory-tools">${tools.map(t=>`<div class="inventory-row"><div><strong>${toolArt(t)} ${esc(t.name)}</strong><span>${esc(t.category)} · ${money(t.price)}/day · ${esc(t.location)}, Tamil Nadu · ${t.available===false?'Maintenance':'Listed'}</span></div><button data-maintenance="${esc(t.id)}" title="Toggle maintenance" aria-label="Toggle maintenance for ${esc(t.name)}">${t.available===false?'↻':'⚙'}</button></div>`).join('')}</div>`; }
function openBooking(toolId){
  if(userRole!=='customer'){toast('Choose the Customer role to book a tool.');$('#role-dialog').showModal();return;}
  const tool=tools.find(t=>t.id===toolId);if(!tool)return;
  const start=$('#search-date').value||today,end=$('#return-date').value||start;
  const available=availability(tool.id,start,end);
  if(!available||tool.available===false){toast('That tool is no longer available for those dates.');runSearch();return;}
  const modal=$('#rental-dialog'),days=daysBetween(start,end),total=days*Number(tool.price);
  $('#dialog-content').innerHTML=`<div class="dialog-inner"><div class="dialog-art" style="--art-bg:${esc(tool.color||'#e8ebde')}">${toolArt(tool)}</div><span class="eyebrow muted-eyebrow">A LITTLE PROJECT MAGIC</span><h2>${esc(tool.name)}</h2><p class="dialog-owner">Hosted by ${esc(tool.owner||'Local host')} · ${esc(tool.location)}, Tamil Nadu · ★ ${Number(tool.rating||4.8).toFixed(1)}</p><p class="dialog-copy">${esc(tool.description||'A handy local tool, ready for your project.')}</p><div class="dialog-price-line"><strong>${money(tool.price)} <span style="font:400 10px var(--sans);color:#858c82">/ day</span></strong><span>${available} available for your dates</span></div><form class="dialog-form" id="rental-form"><div class="form-row"><label>Pick-up date<input type="date" name="startDate" min="${today}" value="${esc(start)}" required></label><label>Return date<input type="date" name="endDate" min="${esc(start)}" value="${esc(end)}" required></label></div><div class="form-row"><label>How many?<select name="quantity">${Array.from({length:available},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')}</select></label><label>Your name<input name="renterName" required placeholder="Your name"></label></div><label>Email address<input type="email" name="email" required placeholder="you@example.com"></label><label>Payment method<select name="paymentMethod"><option>Demo credit / UPI · simulated</option><option>Demo wallet</option></select></label><div class="price-summary"><span>${days} day(s) × ${money(tool.price)} · simulated payment</span><strong id="dialog-total">${money(total)}</strong></div><button class="button button-dark" type="submit" style="width:100%;justify-content:space-between">Confirm & simulate payment <span>↗</span></button><p class="secure-note">Demo checkout only. No real payment is collected or stored.</p></form></div>`;
  modal.showModal();const form=$('#rental-form');
  form.startDate.addEventListener('change',()=>{form.endDate.min=form.startDate.value;if(form.endDate.value<form.startDate.value)form.endDate.value=form.startDate.value;updateTotal();});form.endDate.addEventListener('change',updateTotal);form.quantity.addEventListener('change',updateTotal);
  function updateTotal(){const n=daysBetween(form.startDate.value,form.endDate.value)*Number(tool.price)*Number(form.quantity.value);$('#dialog-total').textContent=money(n);}
  form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const s=data.get('startDate'),e=data.get('endDate'),qty=Number(data.get('quantity'));if(e<s){toast('Return date must be on or after pick-up.');return;}if(availability(tool.id,s,e)<qty){toast('Not enough tools for these dates. Please adjust your request.');return;}
    const rental={id:`BR-${Math.random().toString(36).slice(2,8).toUpperCase()}`,toolId:tool.id,toolName:tool.name,renterName:data.get('renterName'),email:data.get('email'),startDate:s,endDate:e,quantity:qty,total:daysBetween(s,e)*Number(tool.price)*qty,status:'Reserved',createdAt:new Date().toISOString()};rentals.push(rental);persist();
    $('#dialog-content').innerHTML=`<div class="dialog-inner dialog-success"><span class="success-mark">✓</span><span class="eyebrow">YOU’RE ALL SET</span><h2>Project, meet tool.</h2><p>Your request for <strong>${esc(tool.name)}</strong> is reserved.<br>Booking ID <strong>${esc(rental.id)}</strong><br>${prettyDate(s)} – ${prettyDate(e)} · ${money(rental.total)}<br><br>This is a simulated payment; no charge was made.</p><button class="button button-dark" id="view-rentals-button">View my rental <span>↗</span></button></div>`;$('#view-rentals-button').addEventListener('click',()=>{modal.close();setView('rentals');});renderRentals();renderAdmin();runSearch();toast('Rental reserved — payment simulated!');
  });
}
function setRentalStatus(id,status){const rental=rentals.find(r=>r.id===id);if(!rental)return;rental.status=status;persist();renderRentals();renderAdmin();runSearch();toast(`Rental updated to ${status}.`);}
function toggleMaintenance(id){const tool=tools.find(t=>t.id===id);if(!tool)return;tool.available=tool.available===false;persist();renderAdmin();runSearch();toast(`${tool.name} ${tool.available?'is back on the shelf':'marked for maintenance'}.`);}
function render(){ $('#rental-count').textContent=rentals.filter(r=>!['Returned','Cancelled'].includes(statusFor(r))).length;runSearch();if(activeView==='rentals')renderRentals();if(activeView==='admin')renderAdmin(); }
function compressToolImage(file){return new Promise((resolve,reject)=>{if(!file||!/^image\/(jpeg|png|webp|gif)$/i.test(file.type)){reject(new Error('Choose a JPG, PNG, WebP, or GIF image.'));return;}if(file.size>12*1024*1024){reject(new Error('Choose an image smaller than 12 MB.'));return;}const reader=new FileReader();reader.onerror=()=>reject(new Error('The image could not be opened.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('This image could not be previewed.'));image.onload=()=>{const scale=Math.min(1,800/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78));};image.src=reader.result;};reader.readAsDataURL(file);});}
function initializePointerEffects(){
  if(!window.matchMedia('(pointer:fine)').matches)return;
  const halo=document.createElement('div');halo.className='cursor-halo';halo.setAttribute('aria-hidden','true');document.body.appendChild(halo);
  let frame=0,lastX=0,lastY=0;
  document.addEventListener('pointermove',event=>{lastX=event.clientX;lastY=event.clientY;if(frame)return;frame=requestAnimationFrame(()=>{halo.style.left=`${lastX}px`;halo.style.top=`${lastY}px`;halo.classList.add('visible');frame=0;});},{passive:true});
  document.addEventListener('pointerdown',event=>{const target=event.target.closest('button,a.button,.tool-detail-button,.category-chip');if(!target)return;const bounds=target.getBoundingClientRect();const size=Math.max(bounds.width,bounds.height)*1.35;const ripple=document.createElement('span');ripple.className='tap-ripple';ripple.style.width=`${size}px`;ripple.style.height=`${size}px`;ripple.style.left=`${event.clientX-bounds.left-size/2}px`;ripple.style.top=`${event.clientY-bounds.top-size/2}px`;target.classList.remove('button-pressed');target.appendChild(ripple);target.classList.add('button-pressed');setTimeout(()=>{ripple.remove();target.classList.remove('button-pressed');},500);},{passive:true});
}
function initialize(){
  initializePointerEffects();
  updateRoleUI();
  if(oldDemoData||catalogNeedsRefresh)persist();
  const start=$('#search-date'),end=$('#return-date');start.min=today;end.min=today;start.value=datePlus(today,1);end.value=datePlus(today,1);
  start.addEventListener('change',()=>{end.min=start.value;if(end.value<start.value)end.value=start.value;runSearch();});end.addEventListener('change',runSearch);
  $('#search-form').addEventListener('submit',event=>{event.preventDefault();runSearch();$('#marketplace').scrollIntoView({behavior:'smooth'});});
  $('#search-query').addEventListener('input',runSearch);$('#search-location').addEventListener('input',runSearch);
  $$('.category-chip').forEach(chip=>chip.addEventListener('click',()=>{activeCategory=chip.dataset.category;$$('.category-chip').forEach(c=>c.classList.toggle('selected',c===chip));runSearch();}));
  $$('.nav-link').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();setView(link.dataset.view);}));
  $$('[data-open-admin]').forEach(button=>button.addEventListener('click',()=>{changeRole('shopkeeper',false);setView('admin');}));
  $('#profile-button').addEventListener('click',()=>$('#role-dialog').showModal());
  $$('.role-choice').forEach(button=>button.addEventListener('click',()=>changeRole(button.dataset.role)));
  $('#role-dialog-close').addEventListener('click',()=>$('#role-dialog').close());
  $('#role-dialog').addEventListener('click',event=>{if(event.target===$('#role-dialog'))$('#role-dialog').close();});
  $('#mobile-menu').addEventListener('click',()=>$('.main-nav').classList.toggle('open'));
  $('#dialog-close').addEventListener('click',()=>$('#rental-dialog').close());
  $('#rental-dialog').addEventListener('click',event=>{if(event.target===$('#rental-dialog'))$('#rental-dialog').close();});
  $('#tool-image').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{pendingToolImage=await compressToolImage(file);$('#image-preview-photo').src=pendingToolImage;$('#image-preview-name').textContent=file.name;$('#image-upload-preview').classList.remove('hidden');}catch(error){pendingToolImage='';event.target.value='';toast(error.message);}});
  $('#remove-tool-image').addEventListener('click',()=>{pendingToolImage='';$('#tool-image').value='';$('#image-preview-photo').removeAttribute('src');$('#image-upload-preview').classList.add('hidden');});
  $('#add-tool-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get('name')).trim(),category=data.get('category');const tool={id:`t${Date.now()}`,type:inferToolType(name),name,category,emoji:emojiFor(name),price:Number(data.get('price')),location:String(data.get('location')).trim(),owner:'You',initial:'Y',rating:5,reviews:0,quantity:Number(data.get('quantity'))||1,available:true,color:colorFor(category),description:String(data.get('description')||'').trim(),imageData:pendingToolImage};tools.unshift(tool);persist();pendingToolImage='';event.currentTarget.reset();$('#image-preview-photo').removeAttribute('src');$('#image-upload-preview').classList.add('hidden');render();renderAdmin();toast(`${name} is now listed.`);});
  $('#tool-grid').addEventListener('click',event=>{const book=event.target.closest('[data-book]'),favorite=event.target.closest('[data-favorite]');if(book)openBooking(book.dataset.book);if(favorite){const id=favorite.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];persist();runSearch();}});
  $('#suggestion-grid').addEventListener('click',event=>{const book=event.target.closest('[data-book]');if(book)openBooking(book.dataset.book);});
  $('#rentals-list').addEventListener('click',event=>{const cancel=event.target.closest('[data-cancel]'),returned=event.target.closest('[data-return]');if(cancel&&confirm('Cancel this rental request?'))setRentalStatus(cancel.dataset.cancel,'Cancelled');if(returned)setRentalStatus(returned.dataset.return,'Returned');const view=event.target.closest('[data-view]');if(view)setView(view.dataset.view);});
  $('#admin-rentals-list').addEventListener('change',event=>{if(event.target.matches('[data-status]'))setRentalStatus(event.target.dataset.status,event.target.value);});
  $('#admin-inventory-list').addEventListener('click',event=>{const button=event.target.closest('[data-maintenance]');if(button)toggleMaintenance(button.dataset.maintenance);});
  render();
}
function emojiFor(name){return {'hammer':'🔨','screwdriver':'🪛','wrench':'🔧','pliers':'🗜️','drill':'🔩','saw':'🪚','ladder':'🪜','spade':'🌱'}[inferToolType(name)]||'🧰';}
function colorFor(category){return {'Hand tools':'#eee3d5','Power tools':'#e7e4d7','Garden':'#dce8d9','Workshop':'#eee1ce','Home & repair':'#e5e8dc'}[category]||'#e8ebde';}
document.addEventListener('DOMContentLoaded',initialize);
